version: '3'

services:
    grafana:
        image: grafana/grafana:7.4.3
        container_name: grafana
        ports:
            - 3000:3000
    elasticsearch:
        build: ./elasticsearch
        container_name: elasticsearch
        ports:
            - 9200:9200
        expose:
            - 9300